const express = require('express');
const router = express.Router();
const queueService = require('../services/queueService');
const historyService = require('../services/historyService');


// ── Upstash cache helpers ─────────────────────────────────────────────────────
const CACHE_TTL_SECONDS = 60 * 60 * 24; // 24 hours
const UPSTASH_URL   = process.env.UPSTASH_REDIS_REST_URL   || '';
const UPSTASH_TOKEN = process.env.UPSTASH_REDIS_REST_TOKEN || '';

async function cacheGet(key) {
  if (!UPSTASH_URL || !UPSTASH_TOKEN) return null;
  try {
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), 4000);
    const res = await fetch(UPSTASH_URL, {
      method: 'POST',
      headers: { Authorization: `Bearer ${UPSTASH_TOKEN}`, 'Content-Type': 'application/json' },
      body: JSON.stringify(['GET', key]),
      signal: controller.signal
    });
    clearTimeout(timeoutId);
    const data = await res.json();
    const raw = data?.result;
    if (!raw) return null;
    return JSON.parse(typeof raw === 'string' ? raw : JSON.stringify(raw));
  } catch (err) {
    console.error('[Look cacheGet error]', err.message);
    return null;
  }
}

async function cacheSet(key, value) {
  if (!UPSTASH_URL || !UPSTASH_TOKEN) return;
  try {
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), 4000);
    await fetch(UPSTASH_URL, {
      method: 'POST',
      headers: { Authorization: `Bearer ${UPSTASH_TOKEN}`, 'Content-Type': 'application/json' },
      body: JSON.stringify(['SET', key, JSON.stringify(value), 'EX', CACHE_TTL_SECONDS]),
      signal: controller.signal
    });
    clearTimeout(timeoutId);
  } catch (err) {
    console.error('[Look cacheSet error]', err.message);
  }
}


// ── JSON product lookup endpoint (called by client-side JS) ──────────────────
router.get('/:shortcode/products', async (req, res) => {
  try {
    const { shortcode } = req.params;

    const queue = await queueService.getQueue();
    let lookData = queue.find(item => item.shortcode === shortcode);
    
    // Always fetch history to supplement missing data (like productInfo which queue doesn't store directly)
    const history = await historyService.getAll();
    const historyData = history.find(item =>
      item.shortcode === shortcode ||
      item.reelData?.shortcode === shortcode ||
      (item.url || '').includes(`/${shortcode}`)
    );

    if (historyData) {
      if (!lookData) lookData = historyData;
      else {
        // Merge missing productInfo from history if queue item doesn't have it
        if (!lookData.productInfo && historyData.productInfo) {
          lookData.productInfo = historyData.productInfo;
        }
      }
    }

    if (!lookData) return res.json({ found: false, outfit: [] });

    const caption = lookData.caption || lookData.reelData?.caption || lookData.aiContent?.description || '';
    const username = lookData.username || lookData.reelData?.username || '';
    const thumbnailUrl = lookData.thumbnailUrl || lookData.reelData?.thumbnailUrl || '';
    const mediaUrl = lookData.mediaUrl || lookData.reelData?.thumbnailUrl || '';

    let outfit = [];
    const cacheKey = `look_outfit_${shortcode}`;

    if (lookData.productInfo?.outfit?.length > 0) {
      outfit = lookData.productInfo.outfit;
    } else if (lookData.productInfo?.affiliateUrl) {
      outfit.push({
        type: 'Main Piece',
        name: lookData.productInfo.name || 'Featured Item',
        url: lookData.productInfo.affiliateUrl,
        image: thumbnailUrl,
        originalPrice: null
      });
    } else {
      const cached = await cacheGet(cacheKey);
      if (cached && Array.isArray(cached) && cached.length > 0) {
        outfit = cached;
      } else {
        // [Vercel Optimization] 
        // Vercel datacenter IPs are blocked by Flipkart/Amazon.
        // Running live scraping here will always fail after 8.5s, forcing users to stare at a loading screen.
        // Instead, we skip live search. Products MUST be pre-generated by the GitHub Action bot 
        // (which has clean IPs and saves them to history/Upstash).
        // For old posts without pre-generated products, we instantly return an empty array.
        console.warn(`[Look] Live search skipped on Vercel for ${shortcode} (Datacenter IP blocked). Products must be pre-generated by Bot.`);
      }
    }

    return res.json({ found: true, outfit });
  } catch (err) {
    console.error('[Look /products] Error:', err);
    return res.status(500).json({ found: false, outfit: [], error: err.message });
  }
});

// ── Instant HTML shell ─────────────────────────────────────────────────────────
// Fast path: check individual look:{shortcode} key (tiny, <1KB) first.
// Only falls back to full 800KB state download for legacy posts without the index key.
router.get('/:shortcode', async (req, res) => {
  try {
    const { shortcode } = req.params;

    // ── FAST PATH: read individual look index key ─────────────────────────────
    let lookData = await cacheGet(`look:${shortcode}`);
    if (lookData) {
      console.log(`[Look] ⚡ Fast path hit for ${shortcode}`);
    } else {
      // ── SLOW FALLBACK: load full state for legacy posts ──────────────────────
      console.log(`[Look] 🐢 No index key — falling back to full state for ${shortcode}`);
      const [queue, history] = await Promise.all([
        queueService.getQueue(),
        historyService.getAll(),
      ]);
      let found = queue.find(item => item.shortcode === shortcode) || null;
      const historyData = history.find(item =>
        item.shortcode === shortcode ||
        item.reelData?.shortcode === shortcode ||
        (item.url || '').includes(shortcode)
      );
      if (historyData) {
        if (!found) found = historyData;
        else if (!found.productInfo && historyData.productInfo) found.productInfo = historyData.productInfo;
      }
      lookData = found;
    }

    if (!lookData) {
      return res.status(404).send(`
        <html>
        <body style="background:#0f0f11; color:white; font-family:sans-serif; text-align:center; padding:50px;">
          <h2>Look Not Found or Expired</h2>
        </body>
        </html>
      `);
    }

    // ── Build outfit product list from look data ──────────────────────────────
    let outfit = [];
    if (lookData.productInfo?.outfit?.length > 0) {
      outfit = lookData.productInfo.outfit;
    } else if (lookData.productInfo?.affiliateUrl || lookData.affiliateLink) {
      outfit = [{
        type: 'Main Piece',
        name: lookData.productInfo?.name || lookData.aiContent?.title || 'Featured Item',
        url: lookData.productInfo?.affiliateUrl || lookData.affiliateLink,
        image: null,
        originalPrice: null
      }];
    }

    // Normalize fields
    const title = lookData.aiContent?.title || lookData.productInfo?.name || lookData.title || 'Shop The Look';
    const thumbnailUrl = lookData.thumbnailUrl || lookData.reelData?.thumbnailUrl || '';
    const mediaUrl = lookData.mediaUrl || lookData.reelData?.thumbnailUrl || '';

    // Serve instant HTML shell

    const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${title} | Shop The Look</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700;800&display=swap" rel="stylesheet">
  <style>
    :root {
      --bg-color: #09090b;
      --card-bg: rgba(255, 255, 255, 0.03);
      --card-border: rgba(255, 255, 255, 0.08);
      --text-main: #ffffff;
      --text-muted: #a1a1aa;
      --accent: #f43f5e;
      --accent-glow: rgba(244, 63, 94, 0.4);
    }
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: 'Outfit', sans-serif; background-color: var(--bg-color); color: var(--text-main); line-height: 1.5; background-image: radial-gradient(circle at 15% 50%, rgba(244, 63, 94, 0.08), transparent 25%), radial-gradient(circle at 85% 30%, rgba(139, 92, 246, 0.08), transparent 25%); min-height: 100vh; }
    .container { max-width: 540px; margin: 0 auto; padding-bottom: 60px; position: relative; }
    .store-header { position: sticky; top: 0; z-index: 100; padding: 20px; text-align: center; font-weight: 800; font-size: 22px; letter-spacing: 2px; text-transform: uppercase; background: rgba(9, 9, 11, 0.7); backdrop-filter: blur(12px); -webkit-backdrop-filter: blur(12px); border-bottom: 1px solid var(--card-border); display: flex; justify-content: center; align-items: center; gap: 10px; }
    .store-header span { background: linear-gradient(135deg, #fff, #a1a1aa); -webkit-background-clip: text; -webkit-text-fill-color: transparent; }
    .video-section { position: relative; width: 100%; aspect-ratio: 9/16; background: #000; overflow: hidden; box-shadow: 0 20px 40px rgba(0,0,0,0.5); }
    .video-section::after { content: ''; position: absolute; bottom: 0; left: 0; right: 0; height: 150px; background: linear-gradient(to top, var(--bg-color) 0%, transparent 100%); pointer-events: none; }
    video { width: 100%; height: 100%; object-fit: cover; }
    .shop-title-container { padding: 0 24px; margin-top: -30px; position: relative; z-index: 10; margin-bottom: 24px; }
    .shop-title { font-size: 1.5rem; font-weight: 700; display: flex; align-items: center; justify-content: space-between; }
    .item-count { font-size: 0.8rem; font-weight: 600; color: var(--bg-color); background: #fff; padding: 6px 12px; border-radius: 30px; box-shadow: 0 4px 15px rgba(255,255,255,0.2); }
    .product-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 16px; padding: 0 20px; }
    .product-card { background: var(--card-bg); border: 1px solid var(--card-border); border-radius: 16px; overflow: hidden; transition: all 0.3s cubic-bezier(0.25, 0.8, 0.25, 1); backdrop-filter: blur(10px); -webkit-backdrop-filter: blur(10px); }
    .product-card a { text-decoration: none; color: inherit; display: flex; flex-direction: column; height: 100%; }
    .img-wrapper { position: relative; width: 100%; aspect-ratio: 4/5; overflow: hidden; }
    .img-wrapper img { width: 100%; height: 100%; object-fit: cover; transition: transform 0.5s ease; }
    .glass-badge { position: absolute; top: 10px; left: 10px; background: rgba(0,0,0,0.6); backdrop-filter: blur(4px); color: #fff; font-size: 10px; padding: 6px 10px; border-radius: 20px; text-transform: uppercase; letter-spacing: 1px; font-weight: 600; border: 1px solid rgba(255,255,255,0.1); }
    .product-info { padding: 16px; display: flex; flex-direction: column; flex-grow: 1; }
    .product-name { font-size: 0.9rem; font-weight: 500; color: var(--text-main); margin-bottom: 8px; display: -webkit-box; -webkit-line-clamp: 2; -webkit-box-orient: vertical; overflow: hidden; line-height: 1.4; }
    .price { font-weight: 700; font-size: 1rem; margin-bottom: 16px; color: #fff; }
    .buy-button { margin-top: auto; width: 100%; background: rgba(255,255,255,0.1); color: #fff; border: 1px solid rgba(255,255,255,0.2); padding: 12px 0; border-radius: 12px; font-weight: 600; font-size: 0.85rem; cursor: pointer; text-transform: uppercase; letter-spacing: 1px; font-family: 'Outfit', sans-serif; display: flex; align-items: center; justify-content: center; gap: 8px; transition: all 0.3s ease; }
    .product-card:hover { transform: translateY(-5px); box-shadow: 0 15px 30px rgba(0,0,0,0.4); border-color: rgba(255,255,255,0.15); background: rgba(255, 255, 255, 0.05); }
    .product-card:hover .img-wrapper img { transform: scale(1.05); }
    .product-card:hover .buy-button { background: #fff; color: #000; box-shadow: 0 0 20px rgba(255,255,255,0.3); }

    /* Skeleton loader */
    .skeleton { background: linear-gradient(90deg, rgba(255,255,255,0.05) 25%, rgba(255,255,255,0.1) 50%, rgba(255,255,255,0.05) 75%); background-size: 200% 100%; animation: shimmer 1.5s infinite; border-radius: 12px; }
    @keyframes shimmer { 0% { background-position: 200% 0; } 100% { background-position: -200% 0; } }
    .skeleton-card { background: var(--card-bg); border: 1px solid var(--card-border); border-radius: 16px; overflow: hidden; }
    .skeleton-img { width: 100%; aspect-ratio: 4/5; }
    .skeleton-text { height: 14px; margin: 16px 16px 8px; }
    .skeleton-text-short { height: 14px; margin: 0 16px 16px; width: 60%; }
    .skeleton-btn { height: 42px; margin: 0 16px 16px; border-radius: 12px; }

    .loading-msg { grid-column: 1/-1; text-align: center; padding: 20px; color: var(--text-muted); font-size: 0.85rem; }
  </style>
</head>
<body>
  <div class="container">
    <div class="store-header">
      <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M6 2 3 6v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V6l-3-4Z"></path><path d="M3 6h18"></path><path d="M16 10a4 4 0 0 1-8 0"></path></svg>
      <span>Shop The Look</span>
    </div>
    <div class="video-section">
      <video src="${mediaUrl}" poster="${thumbnailUrl}" controls autoplay loop muted playsinline></video>
    </div>
    <div class="shop-title-container">
      <div class="shop-title">
        Curated Outfit
        <span class="item-count" id="item-count">${outfit.length} Items</span>
      </div>
    </div>
    <div class="product-grid" id="product-grid">
    </div>
  </div>

  <script>
    (function() {
      const outfit = ${JSON.stringify(outfit)};
      const grid = document.getElementById('product-grid');
      const fallbackImg = '${thumbnailUrl}';

      if (outfit.length === 0) {
        grid.innerHTML = \`<div style="grid-column:1/-1;text-align:center;padding:40px 20px;color:var(--text-muted)"><div style="font-size:2rem;margin-bottom:12px">🛍️</div><p style="font-size:1rem;font-weight:500;margin-bottom:8px">Products Coming Soon</p><p style="font-size:0.85rem">We're curating the best affiliate links for this look.</p></div>\`;
        return;
      }

      grid.innerHTML = outfit.map(item => \`
        <div class="product-card">
          <a href="\${item.url}" target="_blank" rel="noopener noreferrer">
            <div class="img-wrapper">
              <img src="\${item.image || fallbackImg}" alt="\${item.name}" onerror="this.src='\${fallbackImg}'">
              <div class="glass-badge">\${item.type}</div>
            </div>
            <div class="product-info">
              <h3 class="product-name">\${item.name}</h3>
              <div class="price">\${item.originalPrice ? '₹' + item.originalPrice : 'View Price'}</div>
              <button class="buy-button"><span>Shop Item</span><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M5 12h14"></path><path d="m12 5 7 7-7 7"></path></svg></button>
            </div>
          </a>
        </div>
      \`).join('');
    })();
  </script>
</body>
</html>`;

    res.send(html);
  } catch (err) {
    console.error('[Look Route] Error:', err);
    res.status(500).send('Internal Server Error');
  }
});

module.exports = router;
